# # FROM golang:1.24.0-alpine AS builder
# # WORKDIR /app

# # COPY go.mod go.sum ./
# # RUN go mod download

# # # Copy your book images into the image
# # COPY ../data/books /app/data/books

# # COPY . .
# # RUN go build -o backendservice .

# # FROM alpine:latest
# # WORKDIR /root/
# # COPY --from=builder /app/backendservice .

# # EXPOSE 8080
# # CMD ["./backendservice"]
FROM golang:1.24.0-alpine AS builder
WORKDIR /app

# Copy Go modules
COPY backend/go.mod backend/go.sum ./
RUN go mod download

# Copy backend source code
COPY backend/. . 

# Copy data folder
COPY data/books ./data/books

# Build binary
RUN go build -o backendservice

# Stage 2
FROM alpine:latest
WORKDIR /root/

COPY --from=builder /app/backendservice .

# Copy data
COPY data/books ./data/books

EXPOSE 8080
CMD ["./backendservice"]
