FROM golang:1.24.0-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o cartservice .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/cartservice .

EXPOSE 8082
CMD ["./cartservice"]
