FROM golang:1.24.0-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o wishlistservice .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/wishlistservice .

EXPOSE 8083
CMD ["./wishlistservice"]
